// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react"
import {
  PlasmicRange,
  DefaultRangeProps
} from "./plasmic/achyle_2/PlasmicRange"
import { HTMLElementRefOf } from "@plasmicapp/react-web"

interface RangeProps extends DefaultRangeProps {
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void
  min?: string
  max?: string
  step?: string
}

function Range_ ({ onChange, min, max, step, ...rest }: RangeProps, ref: HTMLElementRefOf<"div">) {

  return <PlasmicRange root={{
    ref, props: {
      min,
      max,
      step,
      onChange
    }
  }} type="range" {...rest} />
}

const Range = React.forwardRef(Range_)
export default Range
