// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicRectangle2,
  DefaultRectangle2Props
} from "./plasmic/achyle_2/PlasmicRectangle2";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Rectangle2Props extends Omit<DefaultRectangle2Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultRectangle2Props altogether and have
// total control over the props for your component.
interface Rectangle2Props extends DefaultRectangle2Props {}

function Rectangle2_(props: Rectangle2Props, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicRectangle2 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicRectangle2 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Rectangle2Props here, but feel free
  // to do whatever works for you.

  return <PlasmicRectangle2 root={{ ref }} {...props} />;
}

const Rectangle2 = React.forwardRef(Rectangle2_);
export default Rectangle2;
