// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9mqNJRrUCJdF1Qi4kUEnK1
// Component: 3Cts4VO6UT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Paragraph from "../../Paragraph"; // plasmic-import: ds4yKdokUn/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../achyle_2/plasmic_achyle_2.module.css"; // plasmic-import: 9mqNJRrUCJdF1Qi4kUEnK1/projectcss
import * as sty from "./PlasmicListItem2.module.css"; // plasmic-import: 3Cts4VO6UT/css

import ListStyleGreenIcon from "../achyle_2/icons/PlasmicIcon__ListStyleGreen"; // plasmic-import: eE8sP416E/icon

export type PlasmicListItem2__VariantMembers = {};

export type PlasmicListItem2__VariantsArgs = {};
type VariantPropType = keyof PlasmicListItem2__VariantsArgs;
export const PlasmicListItem2__VariantProps = new Array<VariantPropType>();

export type PlasmicListItem2__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicListItem2__ArgsType;
export const PlasmicListItem2__ArgProps = new Array<ArgPropType>("children");

export type PlasmicListItem2__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultListItem2Props {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicListItem2__RenderFunc(props: {
  variants: PlasmicListItem2__VariantsArgs;
  args: PlasmicListItem2__ArgsType;
  overrides: PlasmicListItem2__OverridesType;
  dataFetches?: PlasmicListItem2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <ListStyleGreenIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, projectcss.all, sty.svg)}
        role={"img"}
      />

      {p.renderPlasmicSlot({
        defaultContents: (
          <Paragraph
            className={classNames("__wab_instance", sty.paragraph___8FZlh)}
            dark={"dark" as const}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__xlXuM
              )}
            >
              {"Paragraph"}
            </div>
          </Paragraph>
        ),

        value: args.children
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicListItem2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicListItem2__VariantsArgs;
    args?: PlasmicListItem2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicListItem2__Fetches;
  } & Omit<PlasmicListItem2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicListItem2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicListItem2__ArgProps,
      internalVariantPropNames: PlasmicListItem2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicListItem2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicListItem2";
  } else {
    func.displayName = `PlasmicListItem2.${nodeName}`;
  }
  return func;
}

export const PlasmicListItem2 = Object.assign(
  // Top-level PlasmicListItem2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicListItem2
    internalVariantProps: PlasmicListItem2__VariantProps,
    internalArgProps: PlasmicListItem2__ArgProps
  }
);

export default PlasmicListItem2;
/* prettier-ignore-end */
