// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9mqNJRrUCJdF1Qi4kUEnK1
// Component: hVvONWSKSkN
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Heading from "../../Heading"; // plasmic-import: iLkYtMJ5YQ/component
import Paragraph from "../../Paragraph"; // plasmic-import: ds4yKdokUn/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_achyle_2.module.css"; // plasmic-import: 9mqNJRrUCJdF1Qi4kUEnK1/projectcss
import * as sty from "./PlasmicRectangle2.module.css"; // plasmic-import: hVvONWSKSkN/css

import ContractIcon from "./icons/PlasmicIcon__Contract"; // plasmic-import: fMAKgq5kC/icon

export type PlasmicRectangle2__VariantMembers = {};

export type PlasmicRectangle2__VariantsArgs = {};
type VariantPropType = keyof PlasmicRectangle2__VariantsArgs;
export const PlasmicRectangle2__VariantProps = new Array<VariantPropType>();

export type PlasmicRectangle2__ArgsType = {
  image?: React.ReactNode;
  title?: React.ReactNode;
  text?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRectangle2__ArgsType;
export const PlasmicRectangle2__ArgProps = new Array<ArgPropType>(
  "image",
  "title",
  "text"
);

export type PlasmicRectangle2__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRectangle2Props {
  image?: React.ReactNode;
  title?: React.ReactNode;
  text?: React.ReactNode;
  className?: string;
}

function PlasmicRectangle2__RenderFunc(props: {
  variants: PlasmicRectangle2__VariantsArgs;
  args: PlasmicRectangle2__ArgsType;
  overrides: PlasmicRectangle2__OverridesType;
  dataFetches?: PlasmicRectangle2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <ContractIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__o9NTs
            )}
            role={"img"}
          />
        ),

        value: args.image
      })}

      {p.renderPlasmicSlot({
        defaultContents: (
          <Heading
            className={classNames("__wab_instance", sty.heading__kfBaV)}
            dark={"dark" as const}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__rGjE5
              )}
            >
              {"Heading"}
            </div>
          </Heading>
        ),

        value: args.title
      })}

      {p.renderPlasmicSlot({
        defaultContents: (
          <Paragraph
            className={classNames("__wab_instance", sty.paragraph__tfAj3)}
            dark={"dark" as const}
          />
        ),

        value: args.text
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRectangle2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRectangle2__VariantsArgs;
    args?: PlasmicRectangle2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRectangle2__Fetches;
  } & Omit<PlasmicRectangle2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRectangle2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRectangle2__ArgProps,
      internalVariantPropNames: PlasmicRectangle2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRectangle2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRectangle2";
  } else {
    func.displayName = `PlasmicRectangle2.${nodeName}`;
  }
  return func;
}

export const PlasmicRectangle2 = Object.assign(
  // Top-level PlasmicRectangle2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRectangle2
    internalVariantProps: PlasmicRectangle2__VariantProps,
    internalArgProps: PlasmicRectangle2__ArgProps
  }
);

export default PlasmicRectangle2;
/* prettier-ignore-end */
