// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9mqNJRrUCJdF1Qi4kUEnK1
// Component: jYoV5jA9Oa
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_achyle_2.module.css"; // plasmic-import: 9mqNJRrUCJdF1Qi4kUEnK1/projectcss
import * as sty from "./PlasmicRange.module.css"; // plasmic-import: jYoV5jA9Oa/css

export type PlasmicRange__VariantMembers = {};

export type PlasmicRange__VariantsArgs = {};
type VariantPropType = keyof PlasmicRange__VariantsArgs;
export const PlasmicRange__VariantProps = new Array<VariantPropType>();

export type PlasmicRange__ArgsType = {
  type?: string;
};

type ArgPropType = keyof PlasmicRange__ArgsType;
export const PlasmicRange__ArgProps = new Array<ArgPropType>("type");

export type PlasmicRange__OverridesType = {
  root?: p.Flex<"div">;
  undefinedInput?: p.Flex<"input">;
};

export interface DefaultRangeProps {
  type?: string;
  className?: string;
}

function PlasmicRange__RenderFunc(props: {
  variants: PlasmicRange__VariantsArgs;
  args: PlasmicRange__ArgsType;
  overrides: PlasmicRange__OverridesType;
  dataFetches?: PlasmicRange__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <input
        data-plasmic-name={"undefinedInput"}
        data-plasmic-override={overrides.undefinedInput}
        className={classNames(
          defaultcss.input,
          projectcss.input,
          sty.undefinedInput
        )}
        placeholder={"Some placeholder" as const}
        size={1 as const}
        type={args.type}
        value={"Some value" as const}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "undefinedInput"],
  undefinedInput: ["undefinedInput"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  undefinedInput: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRange__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRange__VariantsArgs;
    args?: PlasmicRange__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRange__Fetches;
  } & Omit<PlasmicRange__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRange__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRange__ArgProps,
      internalVariantPropNames: PlasmicRange__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRange__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRange";
  } else {
    func.displayName = `PlasmicRange.${nodeName}`;
  }
  return func;
}

export const PlasmicRange = Object.assign(
  // Top-level PlasmicRange renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    undefinedInput: makeNodeComponent("undefinedInput"),

    // Metadata about props expected for PlasmicRange
    internalVariantProps: PlasmicRange__VariantProps,
    internalArgProps: PlasmicRange__ArgProps
  }
);

export default PlasmicRange;
/* prettier-ignore-end */
