// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9mqNJRrUCJdF1Qi4kUEnK1
// Component: rmbHJKVaT7
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Paragraph from "../../Paragraph"; // plasmic-import: ds4yKdokUn/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_achyle_2.module.css"; // plasmic-import: 9mqNJRrUCJdF1Qi4kUEnK1/projectcss
import * as sty from "./PlasmicFooterListItem.module.css"; // plasmic-import: rmbHJKVaT7/css

export type PlasmicFooterListItem__VariantMembers = {};

export type PlasmicFooterListItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterListItem__VariantsArgs;
export const PlasmicFooterListItem__VariantProps = new Array<VariantPropType>();

export type PlasmicFooterListItem__ArgsType = {
  icon?: React.ReactNode;
  title?: React.ReactNode;
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicFooterListItem__ArgsType;
export const PlasmicFooterListItem__ArgProps = new Array<ArgPropType>(
  "icon",
  "title",
  "children"
);

export type PlasmicFooterListItem__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultFooterListItemProps {
  icon?: React.ReactNode;
  title?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

function PlasmicFooterListItem__RenderFunc(props: {
  variants: PlasmicFooterListItem__VariantsArgs;
  args: PlasmicFooterListItem__ArgsType;
  overrides: PlasmicFooterListItem__OverridesType;
  dataFetches?: PlasmicFooterListItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__hqza
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <svg
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.svg__khLhx
              )}
              role={"img"}
            />
          ),

          value: args.icon
        })}
      </div>

      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__eonhB
        )}
      >
        <Paragraph
          className={classNames("__wab_instance", sty.paragraph__smTsh)}
          dark={"dark" as const}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__yrB5R
                )}
              >
                {"Paragraph"}
              </div>
            ),

            value: args.title
          })}
        </Paragraph>

        <Paragraph
          className={classNames("__wab_instance", sty.paragraph___798Fx)}
          dark={"dark" as const}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Paragraph",
            value: args.children
          })}
        </Paragraph>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterListItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterListItem__VariantsArgs;
    args?: PlasmicFooterListItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFooterListItem__Fetches;
  } & Omit<PlasmicFooterListItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFooterListItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooterListItem__ArgProps,
      internalVariantPropNames: PlasmicFooterListItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFooterListItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterListItem";
  } else {
    func.displayName = `PlasmicFooterListItem.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterListItem = Object.assign(
  // Top-level PlasmicFooterListItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicFooterListItem
    internalVariantProps: PlasmicFooterListItem__VariantProps,
    internalArgProps: PlasmicFooterListItem__ArgProps
  }
);

export default PlasmicFooterListItem;
/* prettier-ignore-end */
